### PR TITLE
activate only when `CMakeLists.txt` is present

### LINKED ISSUE #38: more granular activation events
Currently this extension is always activated which then activates the cmake-tools extensions which for non-cmake projects produces an annoying warning message about not finding a `CMakeLists.txt` file

image

I'd recommend activating on the existence on the existence of a `CMakeLists.txt` in the project (similar to [cmake-tools](https://github.com/microsoft/vscode-cmake-tools/blob/ab01f5057335b2ae27d6841dd3ead9ca5e3e68c4/package.json#L83))

```
  "activationEvents": [
    "workspaceContains:**/CMakeLists.txt",
  ]
```

### PR DESCRIPTION
**Pull request by dvirtz**
fixes #38

### CODE REVIEW

**Review by fredericbonnet — APPROVED** [review]

**Comment by fredericbonnet** [comment]
Thanks for your contribution, it will fix a very annoying behavior! I've added the `hacktoberfest-accepted` label to your PR in case you're participating to the event.

**Comment by dvirtz** [comment]
Thanks, but it's a day too early :-)

**Comment by fredericbonnet** [comment]
The even was already open when I merged the PR, I believe that's because it's already October 1st in the easternmost timezone (UTC+14:00, Kiribati?).

**Comment by dvirtz** [comment]
I don't see it in my profile but that's ok, I didn't think about participating until I read your comment

**Pull request merged**
