### PR TITLE
Add decorations for error messages with file:line info

### PR DESCRIPTION
**Pull request by appden**
This uses a regex adapted from `vscode-cpptools` that detects error messages in a common format used by GCC, Clang, and many other tools to attach error line decorations in the VS Code UI.

### CODE REVIEW

**Comment by fredericbonnet** [comment]
Hi, sorry for the delay and thanks for the contribution! I'll try to evaluate and merge your code ASAP.

**Comment by fredericbonnet** [comment]
Hi again, I wanted to evaluate your PR sooner but real life caught on. I merged your code into the development branch and will build a configurable solution from there that will be part of the next release, thanks again for your contribution!

**Comment by fredericbonnet** [comment]
It's now merged in version [0.17.0](https://github.com/fredericbonnet/cmake-test-explorer/releases/tag/v0.17.0)! See the [README about the new config setting](https://github.com/fredericbonnet/cmake-test-explorer/tree/v0.17.0#error-pattern).

**Comment by appden** [comment]
Thanks so much @fredericbonnet! I really appreciate you looking at this and improving it by making it configurable. 😀

**Pull request merged**
